version: "2"

services:
  app:
    container_name: "app"
    image: "gsm/wildfly"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin123
      - DB_NAME=evogsm
      - DB_USER=root
      - DB_PASS=kis2kakas
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console

  db:
    container_name: "db"
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=evogsm
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=kis2kakas
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./workdir/db/init:/docker-entrypoint-initdb.d # init database
      - ./workdir/db/data:/var/lib/mysql              # data storage
    ports:
      - "3306:3306"

networks:
    default:
        driver: bridge
